defmodule NaiveDice.StripeApi.InMemory do
  def create_charge(source_token, amount, currency) do
    {:ok,
    %{
    amount: amount,
    receipt_number: nil,
    transfer_group: nil,
    transfer: nil,
    customer: nil,
    paid: true,
    refunded: false,
    outcome: %{
      network_status: "approved_by_network",
      reason: nil,
      risk_level: "normal",
      risk_score: 62,
      seller_message: "Payment complete.",
      type: "authorized"
    },
    source_transfer: nil,
    source: %{
      account: nil,
      address_city: nil,
      address_country: nil,
      address_line1: nil,
      address_line1_check: nil,
      address_line2: nil,
      address_state: nil,
      address_zip: nil,
      address_zip_check: nil,
      available_payout_methods: nil,
      brand: "Visa",
      country: "US",
      currency: nil,
      customer: nil,
      cvc_check: "pass",
      default_for_currency: nil,
      dynamic_last4: nil,
      exp_month: 1,
      exp_year: 2021,
      fingerprint: "y3ZYvX4xLyX66f29",
      funding: "credit",
      id: "card_1Df5hJDgTIQFOsYv5kNIFV0e",
      last4: "4242",
      metadata: %{},
      name: "jane@example.com",
      object: "card",
      recipient: nil,
      tokenization_method: nil
    },
    failure_code: nil,
    balance_transaction: "txn_1Df2uNDgTIQFOsYvGvu3EmOQ",                                                                 
    application_fee: nil,                                                                                                
    description: nil,                                                                                                    
    metadata: %{},                                                                                                       
    id: "ch_1Df2uNDgTIQFOsYvpV92Oz8u",                                                                                   
    refunds: %{                                                                                               
      data: [],                                                                                                          
      has_more: false,                                                                                                   
      object: "list",                                                                                                    
      total_count: 0,                                                                                                    
      url: "/v1/charges/ch_1Df2uNDgTIQFOsYvpV92Oz8u/refunds"                                                             
    },                                                                                                                   
    order: nil,                                                                                                          
    on_behalf_of: nil,                                                                                                   
    destination: nil,                                                                                                    
    dispute: nil,                                                                                                        
    livemode: false,                                                                                                     
    captured: true,                                                                                                      
    receipt_email: nil,                                                                                                  
    currency: currency,                                                                                                     
    shipping: nil,                                                                                                       
    fraud_details: %{},                                                                                                  
    status: "succeeded",                                                                                                 
    statement_descriptor: nil,                                                                                           
    failure_message: nil,                                                                                                
    object: "charge",                                                                                                    
    review: nil,                                                                                                         
    created: 1344272067,                                                                                                 
    invoice: nil,                                                                                                        
    application: nil,                                                                                                    
    amount_refunded: 0                                                                                                   
  }}                   
  end
end
